// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxpywvtgpfqyazabsvlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cHl3dnRncGZxeWF6YWJzdmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODk3NTYsImV4cCI6MjA2MzI2NTc1Nn0.0wzTaWhAhF-DHbuuMXhFoAulCEANGJt0G6pRm-sIXxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);